deploymentMode: SingleBinary

loki:
  auth_enabled: false
  useTestSchema: true
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  limits_config:
    volume_enabled: true

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClass: gp2

backend:
  replicas: 0

read:
  replicas: 0

write:
  replicas: 0

test:
  enabled: false

lokiCanary:
  enabled: false

gateway:
  enabled: true
