loki:
  enabled: true
  isDefault: false
  persistence:
    enabled: false

promtail:
  enabled: true

grafana:
  enabled: false
  sidecar:
    datasources:
      enabled: false

prometheus:
  enabled: false

fluent-bit:
  enabled: false

filebeat:
  enabled: false

logstash:
  enabled: false
